theme: just-the-docs

title: Docs Le Nid
description: Aide-mémoire du Nid

url: https://lenid.docs.slowte.ch
baseurl: ''

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"
      
# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  Site principal du Nid:
    - https://lenid.ch
    
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# External navigation links
nav_external_links:

# Show navigation error report
nav_error_report: true # default is false/nil.

# Back to top link
back_to_top: false
#back_to_top_text: "Back to top"

footer_content: '&copy; 2025 Le Nid. Publié sous licence <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0 International</a>. Illustrations par CocoMaterial. Publiées sous licence <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0 1.0 Universal (CC0 1.0) Public Domain Dedication</a>'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
#gh_edit_link_text: "Edit this page on GitHub"
#gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
#gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
#gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
    
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap
